
# this script was generated by ChatGPT to test and verify our implmentation in q2_gradient.py

import numpy as np
from scipy.optimize import fmin_tnc

from q2_gradient import (
    load_train,
    objective_and_grad,
    forward_backward
)


def train_crf(words_x, words_y, d=128, K=26, C=1000):
    """
    Train CRF parameters using TNC optimizer.
    """

    # initialize parameters
    W_init = np.zeros((K, d))
    T_init = np.zeros((K, K))

    params_init = np.concatenate([W_init.ravel(), T_init.ravel()])

    print("Starting training...")

    solution = fmin_tnc(
        func=lambda p, *args: objective_and_grad(p, *args),
        x0=params_init,
        args=(words_x, words_y),
        maxfun=100,
        ftol=1e-3,
        messages=5
    )

    params_opt = solution[0]

    W_opt = params_opt[:K*d].reshape(K, d)
    T_opt = params_opt[K*d:].reshape(K, K)

    print("Training finished.")

    return W_opt, T_opt


def check_last_words(W, T, words_x, words_y, num_words=5):
    """
    Run diagnostics on the last few words in the dataset.
    """

    total_words = len(words_x)

    for i in range(total_words - num_words, total_words):

        print("\n==============================")
        print("Checking word index:", i)
        print("==============================")

        X = words_x[i]
        y = words_y[i]

        log_p, marg_node, marg_edge = forward_backward(X, W, T, y)

        print("Word length:", X.shape[0])
        print("Log probability:", log_p)

        node_sums = np.sum(marg_node, axis=1)
        edge_sums = np.sum(marg_edge, axis=(1, 2))

        print("Node marginal min/max:", np.min(node_sums), np.max(node_sums))
        print("Edge marginal min/max:", np.min(edge_sums), np.max(edge_sums))

        consistency = np.abs(np.sum(marg_edge, axis=2) - marg_node[:-1])

        print("Max node-edge inconsistency:", np.max(consistency))

def inspect_transitions(T):
    """
    Print T values for a few common English transitions and their reverses.
    """
    def idx(c):
        return ord(c) - ord('a')

    pairs = [('q','u'), ('t','h'), ('i','n'), ('e','r'), ('s','t'), ('a','n'), ('o','n')]
    print("\nLearned T values for common transitions:")
    for a,b in pairs:
        print(f"{a} -> {b}: {T[idx(a), idx(b)]:.4f} | {b} -> {a}: {T[idx(b), idx(a)]:.4f}")

def main():

    print("Loading training data...")
    words_x, words_y = load_train("../data/train.txt")

    print("Number of words:", len(words_x))

    W, T = train_crf(words_x, words_y)

    inspect_transitions(T)
    
    print("\nRunning diagnostics on last 5 words...")
    check_last_words(W, T, words_x, words_y, num_words=5)


if __name__ == "__main__":
    main()